{% set version = "2.12.0" %}
{% set name = "tensorflow-base" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tensorflow/text
  git_rev: v{{ version }}
  patches:
    - 0001-fix-build.sh

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # conda build requirements
    - tensorflow {{ version }}
  run:
    - {{ pin_compatible("tensorflow", min_pin="x.x.x", max_pin="x.x") }}

test:
  imports:
    - tensorflow
  commands:
    - conda inspect linkages -p $PREFIX tensorflow-text  # [linux]

about:
  home: https://github.com/tensorflow/text
  license: Apache-2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base package contains only tensorflow.
  description: |
    TensorFlow Text provides a collection of text related classes and ops ready to use with TensorFlow 2.0. The library
    can perform the preprocessing regularly required by text-based models, and includes other features useful for
    sequence modeling not provided by core TensorFlow.
  dev_url: https://github.com/tensorflow/text
  doc_url: https://github.com/tensorflow/text
